menambahkan pengenalan C
teknologi-umum/rosetta pull request #13
Opened 2021-10-05 08:33 UTC by bryanpratama

- **Bahasa**: C
- **Topik** : [01]-pengenalan-C.md
- **Nomor Urut** : 01
- **Tindakan** : (Penambahan)

### Keterangan Lanjut

Apa yang saja yang kamu lakukan?
- menambahkan folder C
- menambahkan file dalam folder C dengan judul "[01]-pengenalan-C"
- merubah README.md pada "bahasa yang tersedia" dengan menambahkan C
- merubah consume.json dengan menambahkan C

2021-10-05 10:27 UTC, elianiva requested changes

2021-10-05 10:27 UTC, elianiva commented on C/[01]-pengenalan-C.md
> +  char name[] = "bryan"; //tipe data yang huruf
lebih pas kalo pake istilah `karakter` aja deh, `char` stands for `character` which translates to `karakter`

2021-10-05 10:27 UTC, elianiva commented on C/[01]-pengenalan-C.md
> +    }
```suggestion
  #include <stdio.h>
  int main(void) {
      printf("Hello, World!\n");
      return 0;
  }
```

2021-10-05 10:27 UTC, elianiva commented on C/[01]-pengenalan-C.md
> +  for(int i = 0; i < 10; i++){
```suggestion
  for (int i = 0; i < 10; i++) {
```

bisa ditambahin `while` atau `do while` juga, terserah sih

2021-10-05 10:27 UTC, elianiva commented on consume.json
> +]
```suggestion
  "C": [
    {
      "id": 1,
      "url": "main/C/[01]-pengenalan-C.md"
    }
  ]
```

2021-10-05 10:27 UTC, elianiva commented on C/[01]-pengenalan-C.md
> +  }
```suggestion
  void main(){
      // memanggil fungsi say_hello()
      say_hello();
  }
```

2021-10-05 10:27 UTC, elianiva commented on C/[01]-pengenalan-C.md
> +  }
```suggestion
  void say_hello() {
      printf("Hello Selamat Datang!\n");
  }
```

2021-10-05 10:27 UTC, elianiva commented on C/[01]-pengenalan-C.md
> +- deklarasi variabel
```suggestion
- Deklarasi Variabel
```

2021-10-05 10:27 UTC, elianiva commented on C/[01]-pengenalan-C.md
> +- mengeluarkan output
```suggestion
- Mengeluarkan Output
```

2021-10-05 10:27 UTC, elianiva commented on C/[01]-pengenalan-C.md
> +Bahasa C juga dijuluki sebagai “God’s programming language” Karena banyak menginspirasi bahasa-bahasa pemrograman yang lain seperti Java, Javascript, C++, C#, PHP, dsb.
```suggestion
Bahasa C juga dijuluki sebagai “God’s programming language” karena banyak menginspirasi bahasa-bahasa pemrograman yang lain seperti Java, Javascript, C++, C#, PHP, dsb.
```

2021-10-05 10:27 UTC, elianiva commented on C/[01]-pengenalan-C.md
> +Bahasa Pemrograman C adalah sebuah bahasa pemrograman komputer yang bisa digunakan untuk membuat berbagai aplikasi (general-purpose programming language),
```suggestion
Bahasa pemrograman C adalah sebuah bahasa pemrograman komputer yang bisa digunakan untuk membuat berbagai aplikasi (general-purpose programming language), 
```

2021-10-05 10:27 UTC, elianiva commented on C/[01]-pengenalan-C.md
> +bahasa assembly (assembly language). Akan tetapi bahasa assembly sendiri sangat rumit dan susah untuk dikembangkan.
menurutku `(assembly language)` ini ngga terlalu penting

2021-10-05 10:27 UTC, elianiva commented on C/[01]-pengenalan-C.md
> +sistem operasi modern saat ini, termasuk Linux, Mac OS (iOS), hingga sistem operasi Android.
`Mac OS` dan `iOS` itu beda, dipisah aja, jangan ditaruh di dalam kurung

2021-10-05 10:27 UTC, elianiva commented on C/[01]-pengenalan-C.md
> +terdapat beberapa kegunaan dari bahasa ini. Termasuk di dalamnya bahasa ini secara original dibangun agar dapat digunakan untuk menuliskan perangkat lunak sistem.
```suggestion
Terdapat beberapa kegunaan dari bahasa ini. Termasuk di dalamnya, bahasa ini awalnya dibangun agar dapat digunakan untuk mengembangkan perangkat lunak sistem.
```

2021-10-05 14:50 UTC, bryanpratama commented on C/[01]-pengenalan-C.md
> +bahasa assembly (assembly language). Akan tetapi bahasa assembly sendiri sangat rumit dan susah untuk dikembangkan.
baik kak nanti aku tata ulang kata- kata nya, maaf kak masih awam dan baru belajar pake github ini kalo mau ngerubah sesuai yang sudah kaka betulin itu pencet "commit suggestion" atau Resolve conversation ya ?

2021-10-05 18:03 UTC, aldy505 commented on C/[01]-pengenalan-C.md
> +bahasa assembly (assembly language). Akan tetapi bahasa assembly sendiri sangat rumit dan susah untuk dikembangkan.
Commit suggestion

2021-10-06 00:20 UTC, artileda requested changes
Luar biasa, tinggal ada berapa perbaikan seperti typo dan tambahan topik.

2021-10-06 00:20 UTC, artileda commented on C/[01]-pengenalan-C.md
> +Secara mendasar, dengan mengetahui bahasa pemrograman C, kita akan mendapatkan sebuah tiket untuk mengetahui hampir seluruh bahasa pemrograman.
Ada baiknya menambahkan C berparadigma apa dan semacamnya, karena ada lingkup paradigma yang tidak di jangkau oleh C seperti paradigma fungsional.

2021-10-06 00:20 UTC, artileda commented on README.md
> +  - [01. Pengenalan C](python/[01]-pengenalan-C.md)
Sesuaikan nama foldernya ya

2021-10-06 02:51 UTC, elianiva approved these changes

2021-10-06 02:55 UTC, bryanpratama commented on C/[01]-pengenalan-C.md
> +Secara mendasar, dengan mengetahui bahasa pemrograman C, kita akan mendapatkan sebuah tiket untuk mengetahui hampir seluruh bahasa pemrograman.
sudah di tambahkan paradigma C

2021-10-06 02:55 UTC, bryanpratama commented on README.md
> +  - [01. Pengenalan C](python/[01]-pengenalan-C.md)
siap sudah dibetulkan kak

2021-10-06 04:00 UTC, aldy505 requested changes
sangat minor typo

2021-10-06 04:00 UTC, aldy505 commented on C/[01]-pengenalan-C.md
> +Terdapat beberapa kegunaan dari bahasa ini. Termasuk di dalamnya, bahasa ini awalnya dibangun agar dapat digunakan untuk mengembangkan perangkat lunak sistem.
```suggestion
Terdapat beberapa kegunaan dari bahasa ini. Termasuk di dalamnya, bahasa ini awalnya dibangun agar dapat digunakan untuk mengembangkan sistem perangkat lunak. 
```

2021-10-06 04:00 UTC, aldy505 commented on C/[01]-pengenalan-C.md
> +bahasa assembly. Akan tetapi bahasa assembly sendiri sangat rumit dan susah untuk dikembangkan.
```suggestion
bahasa Assembly. Akan tetapi bahasa Assembly sendiri sangat rumit dan susah untuk dikembangkan.
```

2021-10-06 04:15 UTC, aldy505 approved these changes
@artileda silahkan di merge

2021-10-06 05:33 UTC, artileda approved these changes
Kerja bagus, selamat ✨✨

2021-10-06 05:33 UTC, merged

2021-10-06 05:36 UTC, bryanpratama commented
@aldy505 @artileda @elianiva terimakasih semuanya