Menambahkan Materi `Variabel dan Tipe Data` pada Bahasa Pemrograman C
teknologi-umum/rosetta pull request #19
Opened 2022-10-03 11:47 UTC by codeOraaange

- **Bahasa**: C
- **Topik** : Variabel dan Tipe Data
- **Nomor Urut** : 02
- **Tindakan** : Penambahan

### Keterangan Lanjut

Apa yang saja yang kamu lakukan?

- menambahkan file [02]-variabel-dan-tipe-data.md dalam folder C
- merubah file README.md
- merubah file consume.json

2022-10-03 13:49 UTC, qepo17 commented on C/[02]-variabel-dan-tipe-data.md
> +Tipe data adalah suatu pengenal yang merupakan bagian program yang paling penting karena tipe data mempengaruhi setiap intruksi yang akan dilaksanakan oleh komputer.
better kasih contoh untuk point ini `setiap intruksi yang akan dilaksanakan oleh komputer`

point ini kurang menjelaskan `Misalnya 5 dibagi 2 saja bisa menghasilkan hasil yang berbeda tergantung tipe datanya`

coba kasih code snippet contoh dari code nya

2022-10-03 13:49 UTC, qepo17 commented on C/[02]-variabel-dan-tipe-data.md
> +Misalnya 5 dibagi 2 saja bisa menghasilkan hasil yang berbeda tergantung tipe datanya. Kita juga harus mengetahui format specifier, apa itu format specifier?
Format Specifier di-enter / jadikan point terpisah dengan tipe data
```
Kita juga harus mengetahui format specifier, apa itu format specifier?
```

2022-10-03 13:49 UTC, qepo17 commented on C/[02]-variabel-dan-tipe-data.md
> +bahasa pemrograman juga harus menggunakan tipe data sebagaimana harusnya.
IMO, better kasih penjelasan secara komputerisasi, variable disimpen di mana? memory. jadi ga `out of nowhere` gitu

Tapi ini CMIIW, apakah perlu dijelasin se detail itu

2022-10-03 13:49 UTC, qepo17 commented on C/[02]-variabel-dan-tipe-data.md
> +Jadi, dalam membuat program, tentu kita sangat membutuhkan variabel. Untuk mengenali variabel tersebut maka harus ada tipe data.
tipe data gausah dimention dulu, fokus ke penjelasan variable. menurutku masih kurang ngena.

point `gelas` itu sebagai `identitas` sedangkan `susu` adalah `data` nya itu belum dapet

2022-10-03 13:49 UTC, qepo17 commented on C/[02]-variabel-dan-tipe-data.md
> +Variabel global adalah variabel yang deklarasinya berada diluar fungsi main atau fungsi manapun sehingga  variabel itu bisa di akses oleh fungsi manapun dan
diluar -> di luar

2022-10-03 13:49 UTC, qepo17 commented on C/[02]-variabel-dan-tipe-data.md
> +Variabel lokal adalah variabel yang deklarasinya berada didalam fungsi, misalnya fungsi main. Sehingga variabel tersebut hanya bisa diakses oleh anggota main
didalam -> di dalam

2022-10-03 13:49 UTC, qepo17 commented on C/[02]-variabel-dan-tipe-data.md
> +- Boolean
ada alasan kenapa `boolean` dipisahin dari tipe data dasar di atasnya?

2022-10-05 01:59 UTC, codeOraaange commented
Pls review again. 
Hatur nuhun.

2022-10-05 05:57 UTC, qepo17 requested changes

2022-10-05 05:57 UTC, qepo17 commented on C/[02]-variabel-dan-tipe-data.md
> +d)	Yang termasuk simbol khusus yang tidak diperbolehan antara lain : !,@,#,$,%,^,&,*,(,),-,+,=.
```
Variabel adalah wadah yang digunakan untuk menampung data/value. Jika dianalogikan, variabel adalah wadah semacam gelas yang didalamnya terdapat air. Atau bisa juga, variabel adalah piring yang didalamnya merupakan makanan.

Variabel adalah identitas, untuk menampung sebuah data/value yang diinginkan.

Berikut adalah aturan dalam penulisan variabel : **(Perlu Diingat)**

Deklarasi variabel adalah sebuah perintah agar program menyediakan variabel yang akan kita pakai. 

a)     Pendeklarasian variabel harus diawali dengan tipe data variabel (pembahasan tipe data akan dibahas pada bagian selanjutnya)

b)	Boleh terdiri dari gabungan huruf dan angka dengan karakter pertama harus huruf.

c)	Bahasa C bersifat case sensitive, artinya huruf besar dan kecil dianggap berbeda. Jadi, antara NAMA, nama dan Nama itu dianggap berbeda.

d)	Tidak boleh mengandung spasi. Tidak Boleh mengandung simbol-simbol khusus, kecuali garis bawah (underscore).

e)	Yang termasuk simbol khusus yang tidak diperbolehan antara lain : !,@,#,$,%,^,&,*,(,),-,+,=.
```

2022-10-05 05:57 UTC, qepo17 commented on C/[02]-variabel-dan-tipe-data.md
> +variabel konstanta harus langsung di inisialisasi/diisi data sesuai dengan tipe data.
di inisialisasi -> diinisialisasi

2022-10-05 15:58 UTC, codeOraaange commented
Sudah diperbaiki ya @qepo17

2022-10-05 23:44 UTC, qepo17 approved these changes
LGTM 👍

2022-10-06 01:41 UTC, codeOraaange commented
Mohon review ulang @aldy505 @izzudin26 @lamualfa  dan `merge` if there is nothing else to review.

2022-10-06 01:52 UTC, aldy505 approved these changes

2022-10-06 01:52 UTC, merged