add(go): pengenalan golang - [01]-pengenalan-go.md
teknologi-umum/rosetta pull request #21
Opened 2023-10-23 03:44 UTC by refaldyrk

- **Bahasa**: Go
- **Topik** : Pengenalan Go
- **Nomor Urut** : 01
- **Tindakan** : (Penambahan)

2023-10-23 03:49 UTC, YogiPristiawan approved these changes

2023-10-23 06:42 UTC, aldy505 requested changes

2023-10-23 06:42 UTC, aldy505 commented on go/[01]-pengenalan-go.md
> +Go dibuat pada tahun 2009, oleh Robert Griesemer, Rob Pike, dan Ken Thompson, semua dari tiga perancang bahasa tidak suka terhadap kompleksitas C++ sehingga menjadi motivasi utama untuk mendesain seb
```suggestion
Go dibuat pada tahun 2009, oleh Robert Griesemer, Rob Pike, dan Ken Thompson, semua dari tiga perancang bahasa tidak suka terhadap kompleksitas C++ sehingga menjadi motivasi utama untuk mendesain sebuah bahasa baru, Go versi 1.0 diluncurkan pada tahun 2012.
```

2023-10-23 06:42 UTC, aldy505 commented on go/[01]-pengenalan-go.md
> +Go merupakan bahasa pemrograman yang dibuat oleh search engine raksasa di masa ini, yaitu google, Go juga terkenal atau fitur yang paling mencolok adalah
```suggestion
Go merupakan bahasa pemrograman yang dibuat oleh search engine raksasa di masa ini, yaitu Google, Go juga terkenal atau fitur yang paling mencolok adalah
```

2023-10-23 06:42 UTC, aldy505 commented on go/[01]-pengenalan-go.md
> +title: Berkenalan Dengan Bahasa Pemrogaman Go
```suggestion
title: Berkenalan Dengan Bahasa Pemrograman Go
```

2023-10-23 06:42 UTC, aldy505 commented on go/[01]-pengenalan-go.md
> +```
Sebaiknya jangan cuma kasih liat kode aja, tapi dijelaskan sekalian.

1. Kode ini apa maksudnya? Apa output yang keluar?
2. Bagaimana cara membaca kode ini?
3. Apa penjelasan dari masing-masing keyword?
4. Bagaimana cara menjalankan kode ini?

2023-10-23 06:42 UTC, aldy505 commented on go/[01]-pengenalan-go.md
> +```
Sama seperti note sebelumnya.

2023-10-23 06:42 UTC, aldy505 commented on go/[01]-pengenalan-go.md
> +```
Sama seperti note sebelumnya.

2023-10-23 06:42 UTC, aldy505 commented on go/[01]-pengenalan-go.md
> +}
Sama seperti note sebelumnya.

2023-10-23 07:13 UTC, YogiPristiawan commented on go/[01]-pengenalan-go.md
> +fitur <b>concurrency</b> nya, Go juga dibuat diatas bahasa pemrograman C, dan Go juga memiliki garbage collection.
```suggestion
fitur <b>concurrency</b> nya, Go juga dibuat di atas bahasa pemrograman C, dan Go juga memiliki garbage collection.
```

2023-10-23 07:14 UTC, YogiPristiawan requested changes

2023-10-23 07:14 UTC, YogiPristiawan commented on go/[01]-pengenalan-go.md
> +fitur <b>concurrency</b> nya, Go juga dibuat diatas bahasa pemrograman C, dan Go juga memiliki garbage collection.
```suggestion
fitur <b>concurrency</b> nya, Go juga dibuat di atas bahasa pemrograman C, dan Go juga memiliki garbage collection.
```

2023-10-23 07:29 UTC, refaldyrk commented
How @aldy505 @YogiPristiawan

2023-10-23 09:22 UTC, YogiPristiawan requested changes

2023-10-23 09:22 UTC, YogiPristiawan commented on go/[01]-pengenalan-go.md
> +Mengapa 5 tidak muncul? karena 5 tidak dibawah 5, simple, jika ingin angka 5 muncul, maka ganti ```i < angka``` menjadi ```i <= angka```.
```suggestion
Mengapa 5 tidak muncul? karena 5 <b>tidak kurang dari</b> 5. Simple, jika ingin angka 5 muncul, maka ganti ```i < angka``` menjadi ```i <= angka```.
```

2023-10-23 14:09 UTC, aldy505 commented on go/[01]-pengenalan-go.md
> +ya, Go akan menjalankan funtion main pertama kali saat program dijalankan.
Ini muter-muter kalimatnya. Coba jelasin satu-satu aja:

1. Apa itu `func`, bagaimana cara bikin fungsi di Go?
2. Jelaskan kenapa nama function `main` itu jadi entrypoint untuk aplikasi Go

2023-10-23 14:11 UTC, aldy505 commented on go/[01]-pengenalan-go.md
> +Karena simplenya Go, akan menjalankan file yang package nya main, atau yang bernama main.
```suggestion
Pada kode diatas selalu menuliskan `package main`, mengapa?
Karena Go akan menjalankan file yang package nya main, atau yang bernama main.
```

Sebetulnya ini agak misleading. "main" bisa dibilang sebagai "package utama" yang bisa dieksekusi sebagai _executable_ (see https://en.wikipedia.org/wiki/Executable). Kalau tujuannya bukan _executable_, bisa pakai nama lain di packagenya.

2023-10-24 04:25 UTC, refaldyrk commented
better? @aldy505 @YogiPristiawan

2023-10-24 08:31 UTC, aldy505 approved these changes

2023-10-24 12:24 UTC, YogiPristiawan requested changes

2023-10-24 12:24 UTC, YogiPristiawan commented on go/[01]-pengenalan-go.md
> +Di Go (Golang), setiap program harus memiliki fungsi main sebagai titik masuk utama atau entry point dari program. Hal ini wajib ada karena main adalah fungsi yang akan dieksekusi pertama kali ketika
```suggestion
Di Go (Golang), setiap program harus memiliki fungsi `main` sebagai titik masuk utama atau entry point dari program. Hal ini wajib ada karena `main` adalah fungsi yang akan dieksekusi pertama kali ketika program dijalankan
```

2023-10-24 14:12 UTC, refaldyrk commented
done @YogiPristiawan

2023-10-24 14:38 UTC, YogiPristiawan approved these changes

2023-10-25 00:47 UTC, merged