add(go): variable dan operator di golang
teknologi-umum/rosetta pull request #22
Opened 2023-10-25 08:13 UTC by refaldyrk

- **Bahasa**: Go
- **Topik** : Variabel Dan Operator
- **Nomor Urut** : 02
- **Tindakan** : (Penambahan)

2023-10-25 08:28 UTC, aldy505 requested changes

2023-10-25 08:28 UTC, aldy505 commented on go/[02]-variable-dan-operator-go.md
> +<li>float32 dan float64: Digunakan untuk bilangan pecahan (floating-point numbers).</li>
Mungkin bisa dijelaskan terkait keberadaan int dengan int8, int16, int32, int64.

2023-10-25 08:28 UTC, aldy505 commented on go/[02]-variable-dan-operator-go.md
> +sisa := a % b
```suggestion
sisa := a % b // disebut juga sebagai modulo atau modulus
```

2023-10-25 08:28 UTC, aldy505 commented on go/[02]-variable-dan-operator-go.md
> +Pointer adalah variabel yang menyimpan alamat memori dari variabel lain. Mereka digunakan untuk mengakses dan memanipulasi variabel asli. Contoh penggunaan pointer:
Pointer itu konsep, bukan variabel.

2023-10-25 08:28 UTC, aldy505 commented on README.md
> +  - [02. Variable Dan Operator Di Golang](go/[02]-variable-dan-operator-go)
Jadi maunya Go apa Golang?

2023-10-25 12:27 UTC, YogiPristiawan requested changes

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +<li>float32 dan float64: Digunakan untuk bilangan pecahan (floating-point numbers).</li>
```suggestion
<li>`int`: Digunakan untuk menyimpan nilai bilangan bulat, misalnya `int` dan `int64`.</li>
<li>`uint`: Digunakan untuk bilangan bulat tanpa tanda (non-negatif), misalnya `uint` dan `uint32`.</li>
<li>`float32` dan `float64`: Digunakan untuk bilangan pecahan (floating-point numbers).</li>
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +<li>rune: Digunakan untuk menyimpan karakter Unicode.</li>
```suggestion
<li>`byte`: Digunakan untuk menyimpan data biner atau karakter tunggal.</li>
<li>`rune`: Digunakan untuk menyimpan karakter [Unicode](https://en.wikipedia.org/wiki/Unicode).</li>
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +<li>array: Digunakan untuk menyimpan kumpulan elemen dengan tipe data yang sama dan ukuran tetap.</li>
```suggestion
<li>`array`: Digunakan untuk menyimpan kumpulan elemen dengan tipe data yang sama dan ukuran tetap.</li>
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +<li>slice: Digunakan untuk menyimpan potongan dari array atau slice lain. Tidak memiliki ukuran tetap.
```suggestion
<li>`slice`: Digunakan untuk menyimpan potongan dari `array` atau slice lain. Tidak memiliki ukuran tetap.
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +<li>map: Digunakan untuk menyimpan pasangan key-value, mirip dengan kamus.</li>
```suggestion
<li>`map`: Digunakan untuk menyimpan pasangan key-value, mirip dengan kamus.</li>
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +<li>struct: Digunakan untuk mendefinisikan tipe data yang dapat memiliki beberapa bidang (fields) dengan tipe data yang berbeda.</li>
```suggestion
<li>`struct`: Digunakan untuk mendefinisikan tipe data yang dapat memiliki beberapa bidang (fields) dengan tipe data yang berbeda.</li>
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +<li>interface: Digunakan untuk mendefinisikan kontrak antara tipe data, memungkinkan polimorfisme.</li>
```suggestion
<li>`interface`: Digunakan untuk mendefinisikan kontrak antara tipe data, memungkinkan polimorfisme.</li>
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +<li><b>string</b> memiliki zero value "" (string kosong).</li>
```suggestion
<li><b>int</b> memiliki zero value `0`.</li>
<li><b>float64</b> memiliki zero value `0.0`.</li>
<li><b>bool</b> memiliki zero value `false`.</li>
<li><b>string</b> memiliki zero value `""` (string kosong).</li>
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +tidakSama := a != b
```suggestion
tidakSamaDengan := a != b
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +Anda dapat membuat pointer dalam Go menggunakan operator & (ampersand) untuk mengambil alamat memori dari suatu nilai, dan operator * (bintang) untuk mengakses nilai yang disimpan di alamat yang diac
```suggestion
Anda dapat membuat pointer dalam Go menggunakan operator `&` (ampersand) untuk mengambil alamat memori dari suatu nilai, dan operator `*` (bintang) untuk mengakses nilai yang disimpan di alamat yang diacu oleh pointer tersebut.
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +iota adalah konstanta yang digunakan dalam konstanta enumerasi. Ini secara otomatis diinkrementasi pada setiap konstanta berikutnya dalam blok konstanta.
```suggestion
`iota` adalah konstanta yang digunakan dalam konstanta enumerasi. Ini secara otomatis diinkrementasi pada setiap konstanta berikutnya dalam blok konstanta.
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +Dalam contoh di atas, iota dimulai dari 0 dan diinkrementasi setiap kali ada konstanta baru.
```suggestion
Dalam contoh di atas, `iota` dimulai dari 0 dan diinkrementasi setiap kali ada konstanta baru.
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +Tipe data int, int8, int16, int32, dan int64 adalah tipe data bilangan (integer) dalam bahasa pemrograman Go, namun, perbedaan utama antara mereka adalah ukuran dan kisaran nilai yang dapat mereka wa
```suggestion
Tipe data `int`, `int8`, `int16`, `int32`, dan `int64` adalah tipe data bilangan (integer) dalam bahasa pemrograman Go, namun, perbedaan utama antara mereka adalah ukuran dan kisaran nilai yang dapat mereka wakili. Mari kita jelaskan masing-masing tipe data ini:
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +<li><b>int</b>: Ini adalah tipe data bilangan bulat yang bergantung pada platform, yang berarti ukuran dan kisaran nilainya dapat berbeda pada sistem yang berbeda. Biasanya, pada sistem 32-bit, tipe
```suggestion
<li><b>int</b>: Ini adalah tipe data bilangan bulat yang bergantung pada platform, yang berarti ukuran dan kisaran nilainya dapat berbeda pada sistem yang berbeda. Biasanya, pada sistem 32-bit, tipe data `int` memiliki ukuran 32 bit dan dapat merepresentasikan nilai antara -2147483648 hingga 2147483647. Pada sistem 64-bit, tipe data `int` memiliki ukuran 64 bit dan dapat merepresentasikan nilai antara -9223372036854775808 hingga 9223372036854775807.
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +<li><b>int8</b>: Tipe data int8 memiliki ukuran 8 bit atau 1 byte. Ini dapat merepresentasikan nilai antara -128 hingga 127.
```suggestion
<li><b>int8</b>: Tipe data `int8` memiliki ukuran 8 bit atau 1 byte. Ini dapat merepresentasikan nilai antara -128 hingga 127.
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +<b>int32</b>: Tipe data int32 memiliki ukuran 32 bit atau 4 byte. Ini dapat merepresentasikan nilai antara -2147483648 hingga 2147483647.
```suggestion
<b>int32</b>: Tipe data `int32` memiliki ukuran 32 bit atau 4 byte. Ini dapat merepresentasikan nilai antara -2147483648 hingga 2147483647.
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +<b>int16</b>: Tipe data int16 memiliki ukuran 16 bit atau 2 byte. Ini dapat merepresentasikan nilai antara -32768 hingga 32767.
```suggestion
<b>int16</b>: Tipe data `int16` memiliki ukuran 16 bit atau 2 byte. Ini dapat merepresentasikan nilai antara -32768 hingga 32767.
```

2023-10-25 12:27 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +<li><b>int64</b>: Tipe data int64 memiliki ukuran 64 bit atau 8 byte. Ini dapat merepresentasikan nilai antara -9223372036854775808 hingga 9223372036854775807.
```suggestion
<li><b>int64</b>: Tipe data `int64` memiliki ukuran 64 bit atau 8 byte. Ini dapat merepresentasikan nilai antara -9223372036854775808 hingga 9223372036854775807.
```

2023-10-26 02:58 UTC, refaldyrk commented
better @aldy505 @YogiPristiawan

2023-10-26 05:55 UTC, YogiPristiawan approved these changes

2023-10-26 05:55 UTC, YogiPristiawan commented on go/[02]-variable-dan-operator-go.md
> +<li> <code> byte </code>: Digunakan untuk menyimpan data biner atau karakter tunggal.</li>
```suggestion
<li> <code>byte</code>: Digunakan untuk menyimpan data biner atau karakter tunggal.</li>
```

2023-10-26 05:56 UTC, YogiPristiawan approved these changes

2023-10-26 05:59 UTC, YogiPristiawan approved these changes

2023-10-26 13:08 UTC, aldy505 approved these changes

2023-10-26 13:08 UTC, merged