add(go): [03]-statement-if-else-go.md
teknologi-umum/rosetta pull request #23
Opened 2023-10-27 02:25 UTC by refaldyrk

- **Bahasa**: Go
- **Topik** : Statement If Else Di Go
- **Nomor Urut** : 03
- **Tindakan** : (Penambahan)

2023-10-27 12:50 UTC, YogiPristiawan requested changes

2023-10-27 12:50 UTC, YogiPristiawan commented on go/[03]-statement-if-else-go.md
> +## Statement If Else Di Go
```suggestion
## Statement `if` `else` di Go
```

2023-10-27 12:50 UTC, YogiPristiawan commented on go/[03]-statement-if-else-go.md
> +}
```suggestion
func main() {
    x := 7 //Deklarasi variable x dengan value 7

    if x > 10 { //buat pernyataan if, jika nilai x lebih dari 10.
        fmt.Println("Nilai x lebih besar dari 10") //Jika pernyataan `if` bernilai `true`, maka jalankan kode berikut
    } else if x > 5 { // Jika nilai x lebih besar dari 
        fmt.Println("Nilai x lebih besar dari 5 tetapi kurang dari atau sama dengan 10") //jika pernyataan `else if` bernilai `true` maka jalankan kode berikut.
    } else { //Buat pernyataan `else` Jika pernyataan `if` dan `else if` bernilai salah (false).
        fmt.Println("Nilai x kurang dari atau sama dengan 5")
    }
}
//Output:  Nilai x lebih besar dari 5 tetapi kurang dari atau sama dengan 10
```

2023-10-27 12:50 UTC, YogiPristiawan commented on go/[03]-statement-if-else-go.md
> +}
```suggestion
func main() {
    x := 3 //Deklarasi variable x dengan value 3

    if x > 5 { //Buat pernyataan if, jika nilai x lebih besar dari 5
        fmt.Println("Nilai x lebih besar dari 5") //Jika x lebih besar dari 5 maka jalankan blok kode berikut.
    } else { //Jika pernyataan if tersebut salah (false), maka jalankan blok kode dibawah.
        fmt.Println("Nilai x kurang dari atau sama dengan 5") //Jika hasil dari pernyataan if adalah salah (false), maka jalankan kode ini.
    }
}
//Output: Nilai x kurang dari atau sama dengan 5.
```

2023-10-30 03:42 UTC, refaldyrk commented
Better? @aldy505 @YogiPristiawan

2023-10-30 04:45 UTC, YogiPristiawan approved these changes

2023-10-30 04:47 UTC, YogiPristiawan requested changes

2023-10-30 04:47 UTC, YogiPristiawan commented on README.md
> +  - [03. Conditional Statement Di Go](go/[03]-statement-if-else-go.md)
```suggestion
  - [03. Conditional Statement di Go](go/[03]-statement-if-else-go.md)
```

2023-10-30 04:47 UTC, YogiPristiawan commented on consume.json
> +      "url": "main/go/[03]-statement-if-else-go.md"
kayaknya perlu ganti filename ya?

2023-10-30 07:10 UTC, refaldyrk commented on consume.json
> +      "url": "main/go/[03]-statement-if-else-go.md"
bentar wkwk

2023-10-31 10:37 UTC, merged